# Generated by Django 5.0.7 on 2024-10-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_profile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
